export const metadata = {
  title: 'Jessica Profile',
  description: 'Generated by Burak Durmuşoğlu',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
